### ISSUE TITLE
Framework - Importar evolución framework "viejo Zahorí" [ZAH-211]

### ISSUE THREAD

**Issue by zahori-io** [zahori-io/zahori-framework#42]
Debido a proyectos Zahorí arrancados de hace tiempo que no se han migrado al framework alojado en GitHub se está introduciendo pequeñas evoluciones en el viejo framework Zahorí alojado en repo Panel

Se debe incorporar estos cambios al repositorio publicado en GitHub:
- Posibilidad de incluir dinámicamente capabilities en zahori.properties mediante el tag testName.
- Posibilidad de emular un dispositivo móvil a través del driver de Chrome.

La estrategia decidida es que no puede haber Zahoris evolucionando en paralelo, todas las modificaciones se deben volcar al Zahorí "oficial"

**Comment by zahori-io** [comment]
Pendiente asignación user Jorge.
Creado pull request en GitHub: https://github.com/zahori-io/zahori-framework/pull/36

**Comment by jmerinoe** [comment]
Asignada a mi

**Comment by jmerinoe** [comment]
Pendiente de incluirse en próxima release zahori-framework

**Comment by zahori-io** [comment]
Esta tarea morirá pero la dejamos para revisión de @joseturegano. Revisar próximo seguimiento o matar

**Comment by zahori-io** [comment]
Decidimos matar!!!!
