### ISSUE TITLE
Framework - Actualizar a Selenium 4 [ZAH-213]

### ISSUE THREAD

**Issue by zahori-io** [zahori-io/zahori-framework#44]
En la capa web estamos utilizando Selenium 3. Ya tiene suficiente estabilidad para plantearnos hacer una migración a la 4.1.

**Comment by zahori-io** [comment]
Me tomo la libertad de asignar a @joseturegano ya que me consta que está trabajando en ello  :)

**Comment by jmerinoe** [comment]
Está aprovechando para eliminar TestNG del framework

**Comment by jmerinoe** [comment]
Se integrará webdriver.io para aprovechar las facilidades que da

**Comment by zahori-io** [comment]
Tarea finalizada por @joseturegano y publicada en versiones v0.2.2 del framework y v0.1.15 del server. Se ha incluido actualización a Java 17

**Comment by zahori-io** [comment]
Actualizado a selenium 4
